import React, { useEffect, useState } from 'react';
import { motion, MotionConfig, useReducedMotion } from 'framer-motion';
import { FiArrowUpRight, FiArrowDown, FiSun, FiMoon, FiGithub, FiLinkedin, FiMail, FiPhone, FiDownload, FiMenu, FiX } from 'react-icons/fi';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';
import './App.css';
const links = ['About', 'Projects', 'Skills', 'Experience', 'Contact'];
const projects = [
  {name:'Shopping cart', type:'APPLICATION', text:'A cart experience with quantity control, persistent state and a simple interface.', tags:['State management','User interface'], path:'personal-projects/shopping-cart', symbol:'01'},
  {name:'Feature delivery reports', type:'ENGINEERING', text:'Release logs and reports documenting how features move through delivery.', tags:['Releases','Documentation'], path:'feature-delivery-reports', symbol:'02'},
  {name:'Personal projects', type:'EXPLORATIONS', text:'Small applications, experiments and ideas built along the way.', tags:['Development','Learning'], path:'personal-projects', symbol:'03'},
];
function Reveal({children, className=''}) { const reduce = useReducedMotion(); return <motion.div className={className} initial={reduce ? false : {opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.12}} transition={{duration:0.6}}>{children}</motion.div>; }
function App(){
  const [dark,setDark]=useState(()=>{try{return localStorage.getItem('theme') !== 'light';}catch{return true;}});
  const [menu,setMenu]=useState(false);
  const [status,setStatus]=useState('idle');
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('theme',dark?'dark':'light');}catch{}},[dark]);
  async function send(e){e.preventDefault();const form=e.currentTarget;setStatus('sending');try{const res=await fetch('https://formsubmit.co/ajax/zjsarath@gmail.com',{method:'POST',body:new FormData(form)});const data=await res.json();if(!res.ok || (data.success !== true && data.success !== 'true'))throw new Error();setStatus('sent');form.reset();}catch{setStatus('error');}}
  return <MotionConfig reducedMotion="user"><a className="skip" href="#main">Skip to content</a>
    <header className="header"><a href="#home" className="wordmark" aria-label="Sarath home">sarath<span>®</span></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation">{links.map(link=><a href={'#'+link.toLowerCase()} key={link} onClick={()=>setMenu(false)}>{link}</a>)}</nav><div className="header-actions"><button className="icon-button" aria-label={dark?'Use light theme':'Use dark theme'} onClick={()=>setDark(!dark)}>{dark?<FiSun/>:<FiMoon/>}</button><a className="header-contact" href="mailto:zjsarath@gmail.com">Let’s talk <FiArrowUpRight/></a><button className="icon-button menu" aria-expanded={menu} aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<FiX/>:<FiMenu/>}</button></div></header>
    <main id="main"><section id="home" className="hero wrap"><Reveal className="hero-copy"><div className="eyebrow">SOFTWARE DEVELOPER & QUALITY ENGINEER</div><h1>Thoughtful code.<br/>Reliable systems.<br/><span>A human touch.</span></h1><div className="intro"><span className="intro-line"/><p>I’m Sarath Ramachandran. I build intuitive experiences with React and Java, with a quality-first approach to everything I ship.</p></div><div className="hero-actions"><a className="button primary" href="#projects">Explore my work <FiArrowUpRight/></a><a className="text-link" href="#resume">Download CV <FiDownload/></a></div></Reveal><Reveal className="portrait-area"><div className="portrait-frame"><div className="portrait-label">THE PERSON BEHIND THE CODE</div><img src={`${process.env.PUBLIC_URL}/sarath.png`} alt="Sarath Ramachandran" fetchPriority="high"/><div className="portrait-caption"><span>Sarath R.</span><span>Developer. Problem solver.</span></div></div><div className="floating-tag">&lt;/&gt; <span>Built with curiosity.</span></div></Reveal><div className="hero-bottom"><span>REACT / JAVA / SPRING BOOT</span><a href="#about">A little more about me <FiArrowDown/></a></div></section>
    <section id="about" className="section wrap"><Reveal className="section-grid"><div className="section-label">01 / ABOUT</div><div><h2>Curious by nature.<br/><span className="muted">Engineer by practice.</span></h2><div className="about-columns"><p>I’m a software and quality engineer at William Hill, growing into full-stack development. I enjoy taking complex ideas and turning them into experiences that feel simple.</p><p>Testing has shaped how I build: think through the edge cases, understand the user and make it reliable. Away from the keyboard, you’ll find me exploring photography, travel and the outdoors.</p></div></div></Reveal></section>
    <section id="projects" className="section wrap"><Reveal><div className="section-heading"><div><div className="section-label">02 / SELECTED WORK</div><h2>From idea to interaction.</h2></div><a className="text-link" href="https://github.com/zjsarath" target="_blank" rel="noreferrer">All repositories <FiArrowUpRight/></a></div></Reveal><div className="project-grid">{projects.map(p=><Reveal key={p.name}><a className="project" href={'https://github.com/zjsarath/zjsarath/tree/main/'+p.path} target="_blank" rel="noreferrer"><div className="project-top"><span>{p.type}</span><FiArrowUpRight/></div><div className="project-number" aria-hidden="true">{p.symbol}<span> /</span></div><h3>{p.name}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><span className="project-link">Explore source <FiArrowUpRight/></span></a></Reveal>)}</div></section>
    <section id="skills" className="section wrap"><Reveal className="section-grid"><div className="section-label">03 / TOOLKIT</div><div><h2>The tools behind the work.</h2>{[['01','Frontend','React','Redux','JavaScript','HTML & CSS'],['02','Backend','Java','Spring Boot','Kafka','DynamoDB'],['03','Quality','TestCafe','Cypress','Jest','JUnit','Selenium'],['04','Workflow','Git','GitLab CI/CD','Postman','IntelliJ','Agile / Scrum']].map(([n,title,...skills])=><div className="skill-row" key={n}><span className="row-number">{n}</span><h3>{title}</h3><div className="tags">{skills.map(s=><span key={s}>{s}</span>)}</div></div>)}</div></Reveal></section>
    <section id="experience" className="section wrap"><Reveal className="section-grid"><div className="section-label">04 / THE JOURNEY</div><div><h2>Learning. Building. Growing.</h2><article className="experience"><div className="experience-top"><h3>William Hill</h3><span>Nov 2023 — Present</span></div><h4>Software Quality Engineer</h4><p>Manual and automated testing, React and Java development, and feature delivery reporting. Working across development and quality to help deliver reliable software.</p></article><article className="experience"><div className="experience-top"><h3>QA Ltd</h3><span>2023 — 2026</span></div><h4>Level 4 Software Developer Apprenticeship</h4><p>Java, web development, the software development lifecycle, Agile and testing.</p></article><div id="resume" className="resume"><span>Want the full picture?</span><a className="button secondary" href={`${process.env.PUBLIC_URL}/resume.pdf`} download>Download my CV <FiDownload/></a></div></div></Reveal></section>
    <section id="contact" className="contact-section"><div className="wrap"><Reveal className="contact-grid"><div><div className="section-label">05 / WHAT’S NEXT?</div><h2>Good things start<br/>with a <span>hello.</span></h2><p>Have a project in mind, an opportunity to share, or just want to connect? I’d love to hear from you.</p><a className="email" href="mailto:zjsarath@gmail.com">zjsarath@gmail.com <FiArrowUpRight/></a><div className="socials"><a href="https://github.com/zjsarath" aria-label="GitHub"><FiGithub/></a><a href="https://www.linkedin.com/in/sarathrc" aria-label="LinkedIn"><FiLinkedin/></a><a href="mailto:zjsarath@gmail.com" aria-label="Email"><FiMail/></a><a href="tel:+447721703679" aria-label="Telephone"><FiPhone/></a></div></div><form onSubmit={send}><label htmlFor="name">Your name</label><input id="name" name="name" autoComplete="name" placeholder="Alex Smith" required maxLength={200}/><label htmlFor="email">Email address</label><input id="email" type="email" name="email" autoComplete="email" placeholder="alex@example.com" required/><label htmlFor="message">What’s on your mind?</label><textarea id="message" name="message" rows="3" placeholder="Tell me a little about it…" required maxLength={10000}/><button className="button primary" disabled={status==='sending'}>{status==='sending'?'Sending…':'Send message'} <FiArrowUpRight/></button><p className="form-status" role="status">{status==='sent'?'Thanks for reaching out. Your message has been sent.':status==='error'?'Couldn’t send your message. Please try again or email me directly.':''}</p></form></Reveal></div></section></main><footer className="wrap"><a href="#home" className="wordmark">sarath<span>®</span></a><span>© {new Date().getFullYear()} Sarath Ramachandran</span><a href="#home">Back to top ↑</a></footer></MotionConfig>;
}
export default App;
